---
- name: "Ensure required dependencies are present"
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    # python is python2
    - "python"
    - "python-pip"
    - "libssl-dev"
    - "libcurl4-openssl-dev"
   # Required to handle gif images
    - "gifsicle"

- name: "Ensure optional dependencies are present"
  package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ thumbor_optional_dependencies | default([]) }}"
