---
- name: "Ensure the thumbor group is present"
  group:
    name: "thumbor"
    system: "yes"

- name: "Ensure the thumbor user is present"
  user:
    name: "thumbor"
    shell: "/bin/false"
    group: "thumbor"
    system: "yes"

- name: "Ensure latest version of thumbor application is present"
  pip:
    executable: "pip2"
    name: "thumbor"
    state: "latest"
  when: (thumbor_version is undefined)

- name: "Ensure specific version of thumbor application is present"
  pip:
    executable: "pip2"
    name: "thumbor"
    state: "present"
    version: "{{ thumbor_version }}"
  when: (thumbor_version is defined)

- name: "Enforce the thumbor configuration directory"
  file:
    owner: "thumbor"
    group: "thumbor"
    path: "/etc/thumbor/"
    state: "directory"
    mode: "0755"

- name: "Enforce the configuration files"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "u=rw,g=r,o=r"
  with_items:
    - src: "etc/default/thumbor.j2"
      dest: "/etc/default/thumbor"
    - src: "etc/systemd/system/thumbor.service.j2"
      dest: "/etc/systemd/system/thumbor.service"
    - src: "etc/thumbor/thumbor.conf.j2"
      dest: "/etc/thumbor/thumbor.conf"
      owner: "thumbor"
      group: "thumbor"
  notify:
    - "restart thumbor"
